{{- if .Values.wiremock_istance_local.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wiremock.serviceAccountName" . }}
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
  {{- with .Values.wiremock_istance_local.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
