apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql_instance_local.deployment.name | quote }}
  labels:
    app: {{ .Values.mysql_instance_local.deployment.name | quote }}
spec:
  replicas: {{ .Values.mysql_instance_local.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mysql_instance_local.deployment.name | quote }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql_instance_local.deployment.name | quote }}
    spec:
      {{- if .Values.mysql_instance_local.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.mysql_instance_local.imagePullSecrets.name | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.mysql_instance_local.deployment.container.name | quote }}
          image: "{{ .Values.mysql_instance_local.image.repository }}:{{ .Values.mysql_instance_local.image.tag }}"
          imagePullPolicy: {{ .Values.mysql_instance_local.image.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.mysql_instance_local.deployment.container.port }}
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
                - "--silent"
            initialDelaySeconds: {{ .Values.mysql_instance_local.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql_instance_local.probes.liveness.periodSeconds }}
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
                - "--silent"
            initialDelaySeconds: {{ .Values.mysql_instance_local.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql_instance_local.probes.readiness.periodSeconds }}
          resources:
            limits:
              cpu: {{ .Values.mysql_instance_local.resources.limits.cpu }}
              memory: {{ .Values.mysql_instance_local.resources.limits.memory }}
            requests:
              cpu: {{ .Values.mysql_instance_local.resources.requests.cpu }}
              memory: {{ .Values.mysql_instance_local.resources.requests.memory }}
