apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
    name: {{ .Values.spring_instance_local.deployment.name }}
    labels:
        app: {{ .Values.spring_instance_local.deployment.name }}
spec:
    replicas: {{ .Values.spring_instance_local.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Values.spring_instance_local.deployment.name }}
    strategy:
        canary:
            steps:
                - setWeight: 20
                - pause: {}                
                - setWeight: 50
                - pause: {}
                - setWeight: 100
    template:
        metadata:
            labels:
                app: {{ .Values.spring_instance_local.deployment.name }}
        spec:
            {{- if .Values.spring_instance_local.imagePullSecrets.enabled }}
            imagePullSecrets:
                - name: {{ .Values.spring_instance_local.imagePullSecrets.name }}
            {{- end }}
            containers:
                - name: {{ .Values.spring_instance_local.deployment.container.name }}
                  image: "{{ .Values.spring_instance_local.image.repository }}:{{ .Values.spring_instance_local.image.tag }}"
                  imagePullPolicy: {{ .Values.spring_instance_local.image.pullPolicy }}
                  ports:
                      - containerPort: {{ .Values.spring_instance_local.deployment.container.port }}
                  env:
                      - name: JAVA_HOME
                        valueFrom:
                        configMapKeyRef:
                            name: {{ .Values.spring_instance_local.configMap.name }}
                            key: JAVA_HOME
                  resources:
                      limits:
                          cpu: {{ .Values.spring_instance_local.resources.limits.cpu }}
                          memory: {{ .Values.spring_instance_local.resources.limits.memory }}
                      requests:
                          cpu: {{ .Values.spring_instance_local.resources.requests.cpu }}
                          memory: {{ .Values.spring_instance_local.resources.requests.memory}}
