apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
    name: {{ .Values.mysql_instance_local_2.deployment.name }}
    labels:
        app: {{ .Values.mysql_instance_local_2.deployment.name }}
spec:
    replicas: {{ .Values.mysql_instance_local_2.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Values.mysql_instance_local_2.deployment.name }}
    strategy:
        canary:
            steps:
                - setWeight: 20
                - pause: {}                
                - setWeight: 50
                - pause: {}
                - setWeight: 100
    template:
        metadata:
            labels:
                app: {{ .Values.mysql_instance_local_2.deployment.name }}
        spec:
            {{- if .Values.mysql_instance_local_2.imagePullSecrets.enabled }}
            imagePullSecrets:
                - name: {{ .Values.mysql_instance_local_2.imagePullSecrets.name }}
            {{- end }}
            containers:
                - name: {{ .Values.mysql_instance_local_2.deployment.container.name }}
                  image: "{{ .Values.mysql_instance_local_2.image.repository }}:{{ .Values.mysql_instance_local_2.image.tag }}"
                  imagePullPolicy: {{ .Values.mysql_instance_local_2.image.pullPolicy }}
                  ports:
                      - containerPort: {{ .Values.mysql_instance_local_2.deployment.container.port }}
                  resources:
                      limits:
                          cpu: {{ .Values.mysql_instance_local_2.resources.limits.cpu }}
                          memory: {{ .Values.mysql_instance_local_2.resources.limits.memory }}
                      requests:
                          cpu: {{ .Values.mysql_instance_local_2.resources.requests.cpu }}
                          memory: {{ .Values.mysql_instance_local_2.resources.requests.memory}}
