apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiremock.fullname" . }}-responses-configs
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $key, $value := $files }}
  {{- if hasPrefix "responses/" $key }}
  {{ $key | trimPrefix "responses/" | replace "/" "_" }}: |
    {{ $files.Get $key | indent 4 }}
  {{- end }}
  {{- end }}
  {{- with .Values.wiremock_istance_local.responses }}
  {{- toYaml . | nindent 2 }}
  {{- end }}