apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wiremock.fullname" . }}-mappings-configs
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $key, $value := .Files }}
  {{- if hasPrefix $key "mappings/" }} {{/* only when in mappings/ */}}
  {{ $key | trimPrefix "mappings/" | replace "/" "_" }}: {{ $files.Get $key | quote }} {{/* adapt $key as desired */}}
  {{- end }}
  {{- end }}
  {{- with .Values.wiremock_istance_local.mappings }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
