apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wiremock_instance_local.deployment.name }}
  labels:
    app: {{ .Values.wiremock_instance_local.deployment.name }}
spec:
  replicas: {{ .Values.spring_instance_local.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.spring_instance_local.deployment.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.spring_instance_local.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.spring_instance_local.deployment.container.name }}
        image: "{{ .Values.spring_instance_local.image.repository }}:{{ .Values.spring_instance_local.image.tag }}"
        imagePullPolicy: {{ .Values.spring_instance_local.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.spring_instance_local.deployment.container.port }}
        volumeMounts:
        - name: mappings-data
          mountPath: /home/wiremock/mappings
        - name: responses-data
          mountPath: /home/wiremock/__files
        livenessProbe:
          httpGet:
            path: /__admin/health
            port: {{ .Values.wiremock_instance_local.service.internalPort }}
            scheme: {{ .Values.wiremock_instance_local.scheme }}
        readinessProbe:
          httpGet:
            path: /__admin/health
            port: {{ .Values.wiremock_instance_local.service.internalPort }}
            scheme: {{ .Values.wiremock_instance_local.scheme }}
        resources:
          limits:
            cpu: {{ .Values.spring_instance_local.resources.limits.cpu }}
            memory: {{ .Values.spring_instance_local.resources.limits.memory }}
          requests:
            cpu: {{ .Values.spring_instance_local.resources.requests.cpu }}
            memory: {{ .Values.spring_instance_local.resources.requests.memory }}
      volumes:
      - name: mappings-data
        hostPath:
          path: "/mnt/c/Users/joao.a.ferreira/OneDrive - ANF - Associação Nacional das Farmácias/Desktop/Tarefas/R
epos/mappings"
          type: Directory
      - name: responses-data
        hostPath:
          path: "/mnt/c/Users/joao.a.ferreira/OneDrive - ANF - Associação Nacional das Farmácias/Desktop/Tarefas/R
epos/responses"
          type: Directory
