apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wiremock_instance_local.deployment.name }}
  labels:
    app: {{ .Values.wiremock_instance_local.deployment.name }}
spec:
  replicas: {{ .Values.wiremock_instance_local.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.wiremock_instance_local.deployment.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.wiremock_instance_local.deployment.name }}
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command: ['sh', '-c', 'rm -rf /storage && mkdir -p /storage && git clone https://github.com/joaoferreira15/Wiremock.git /storage && cp -r /storage/wiremock/mappings/* /storage/mappings/ && cp -r /storage/wiremock/responses/* /storage/responses/']
        volumeMounts:
        - name: mappings-data
          mountPath: /storage/mappings
        - name: responses-data
          mountPath: /storage/responses
      containers:
      - name: {{ .Values.wiremock_instance_local.deployment.container.name }}
        image: "{{ .Values.wiremock_instance_local.image.repository }}:{{ .Values.wiremock_instance_local.image.tag }}"
        imagePullPolicy: {{ .Values.wiremock_instance_local.image.pullPolicy }}
        args: {{ .Values.wiremock_instance_local.args }}
        ports:
        - containerPort: {{ .Values.wiremock_instance_local.deployment.container.port }}
        volumeMounts:
        - name: mappings-data
          mountPath: /home/wiremock/mappings
        - name: responses-data
          mountPath: /home/wiremock/__files
        livenessProbe:
          httpGet:
              path: /__admin/health
              port: {{ .Values.wiremock_instance_local.deployment.container.port }}
          initialDelaySeconds: {{ .Values.wiremock_instance_local.probes.liveness.initialDelaySeconds }}
          periodSeconds:  {{ .Values.wiremock_instance_local.probes.liveness.periodSeconds }}
        resources:
          limits:
            cpu: {{ .Values.wiremock_instance_local.resources.limits.cpu }}
            memory: {{ .Values.wiremock_instance_local.resources.limits.memory }}
          requests:
            cpu: {{ .Values.wiremock_instance_local.resources.requests.cpu }}
            memory: {{ .Values.wiremock_instance_local.resources.requests.memory }}
      volumes:
      - name: mappings-data
        emptyDir: {}
      - name: responses-data
        emptyDir: {}