apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiremock.fullname" . }}
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
spec:
  {{- if not .Values.wiremock_istance_local.autoscaling.enabled }}
  replicas: {{ .Values.wiremock_istance_local.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wiremock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "wiremock.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "wiremock.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.wiremock_istance_local.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wiremock.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.wiremock_istance_local.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.wiremock_istance_local.securityContext | nindent 12 }}
          image: "{{ .Values.wiremock_istance_local.image.repository }}:{{ .Values.wiremock_istance_local.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.wiremock_istance_local.image.pullPolicy }}
          {{- with .Values.wiremock_istance_local.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.wiremock_istance_local.args }}
          args:
          {{- range .Values.wiremock_istance_local.args }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.wiremock_istance_local.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /__admin/health
              port: {{ .Values.wiremock_istance_local.service.internalPort }}
              scheme: {{ .Values.wiremock_istance_local.scheme }}
          readinessProbe:
            httpGet:
              path: /__admin/health
              port: {{ .Values.wiremock_istance_local.service.internalPort }}
              scheme: {{ .Values.wiremock_istance_local.scheme }}
          resources:
            {{- toYaml .Values.wiremock_istance_local.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/wiremock/storage/mappings
              name: mappings-data
            - mountPath: /home/wiremock/storage/__files
              name: responses-data
      initContainers:
        - name: copy-mappings
          securityContext:
            {{- toYaml .Values.wiremock_istance_local.securityContext | nindent 12 }}
          image: "{{ .Values.wiremock_istance_local.initContainer.image.repository }}:{{ .Values.wiremock_istance_local.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.wiremock_istance_local.initContainer.image.pullPolicy }}
          command: ["bash", "-c", "cp  -rf /data/mappings /home/wiremock/storage/mappings"]
          volumeMounts:
            - mountPath: /data/mappings
              name: mappings-volume
            - mountPath: /home/wiremock/storage/mappings
              name: mappings-data
        - name: copy-responses
          securityContext:
            {{- toYaml .Values.wiremock_istance_local.securityContext | nindent 12 }}
          image: "{{ .Values.wiremock_istance_local.initContainer.image.repository }}:{{ .Values.wiremock_istance_local.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.wiremock_istance_local.initContainer.image.pullPolicy }}
          command: ["bash", "-c", "cp  -rf /data/responses /home/wiremock/storage/__files"]
          volumeMounts:
            - mountPath: /data/responses
              name: responses-volume
            - mountPath: /home/wiremock/storage/__files
              name: responses-data
      {{- with .Values.wiremock_istance_local.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wiremock_istance_local.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wiremock_istance_local.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
volumes:
  - name: mappings-data
    hostPath:
      path: "/mnt/c/Users/joao.a.ferreira/OneDrive - ANF - Associação Nacional das Farmácias/Desktop/Tarefas/Repos/mappings"
      type: Directory
  - name: responses-volume
    hostPath:
      path: "/mnt/c/Users/joao.a.ferreira/OneDrive - ANF - Associação Nacional das Farmácias/Desktop/Tarefas/Repos/responses"
      type: Directory
