apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wiremock_instance_local.deployment.name }}
  labels:
    app: {{ .Values.wiremock_instance_local.deployment.name }}
spec:
  replicas: {{ .Values.wiremock_instance_local.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.wiremock_instance_local.deployment.name }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.wiremock_instance_local.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.wiremock_instance_local.deployment.container.name }}
        image: "{{ .Values.wiremock_instance_local.image.repository }}:{{ .Values.wiremock_instance_local.image.tag }}"
        imagePullPolicy: {{ .Values.wiremock_instance_local.image.pullPolicy }}
        args: {{ .Values.wiremock_instance_local.args }}
        ports:
        - containerPort: {{ .Values.wiremock_instance_local.deployment.container.port }}
        volumeMounts:
        - name: mappings-data
          mountPath: /home/wiremock/mappings
        - name: responses-data
          mountPath: /home/wiremock/__files
        livenessProbe:
          httpGet:
              path: /__admin/health
              port: {{ .Values.wiremock_instance_local.deployment.container.port }}
          initialDelaySeconds: {{ .Values.wiremock_instance_local.probes.liveness.initialDelaySeconds }}
          periodSeconds:  {{ .Values.wiremock_instance_local.probes.liveness.periodSeconds }}
        resources:
          limits:
            cpu: {{ .Values.wiremock_instance_local.resources.limits.cpu }}
            memory: {{ .Values.wiremock_instance_local.resources.limits.memory }}
          requests:
            cpu: {{ .Values.wiremock_instance_local.resources.requests.cpu }}
            memory: {{ .Values.wiremock_instance_local.resources.requests.memory }}
      volumes:
      - name: mappings-data
        hostPath:
          path: '/mnt/c/Users/joao.a.ferreira/OneDrive - ANF - Associação Nacional das Farmácias/Desktop/Tarefas/Repos/responses'
          type: Directory
      - name: responses-data
        hostPath:
          path: '/mnt/c/Users/joao.a.ferreira/OneDrive - ANF - Associação Nacional das Farmácias/Desktop/Tarefas/Repos/responses'
          type: Directory
