apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "wiremock.fullname" . }}
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
spec:
  {{- if not .Values.wiremock_instance_local.autoscaling.enabled }}
  replicas: {{ .Values.wiremock_instance_local.replicaCount }}
  {{- end }}
  strategy:
        canary:
            steps:
                - setWeight: 20
                - pause: {}                
                - setWeight: 50
                - pause: {}
                - setWeight: 100
  selector:
    matchLabels:
      {{- include "wiremock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "wiremock.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "wiremock.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.wiremock_instance_local.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wiremock.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.wiremock_instance_local.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.wiremock_instance_local.securityContext | nindent 12 }}
          image: "{{ .Values.wiremock_instance_local.image.repository }}:{{ .Values.wiremock_instance_local.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.wiremock_instance_local.image.pullPolicy }}
          {{- with .Values.wiremock_instance_local.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.wiremock_instance_local.args }}
          args:
          {{- range .Values.wiremock_instance_local.args }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.wiremock_instance_local.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /__admin/health
              port: {{ .Values.wiremock_instance_local.service.internalPort }}
              scheme: {{ .Values.wiremock_instance_local.scheme }}
            initialDelaySeconds: {{ .Values.wiremock_instance_local.probes.liveness.initialDelaySeconds }}
            periodSeconds:  {{ .Values.wiremock_instance_local.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /__admin/mappings
              port: {{ .Values.wiremock_instance_local.service.internalPort }}
              scheme: {{ .Values.wiremock_instance_local.scheme }}
            initialDelaySeconds: {{ .Values.wiremock_instance_local.probes.liveness.initialDelaySeconds }}
            periodSeconds:  {{ .Values.wiremock_instance_local.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.wiremock_instance_local.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/wiremock/storage/mappings
              name: mappings-data
            - mountPath: /home/wiremock/storage/__files
              name: responses-data
      initContainers:
        - name: copy-mappings
          securityContext:
            {{- toYaml .Values.wiremock_instance_local.securityContext | nindent 12 }}
          image: "{{ .Values.wiremock_instance_local.initContainer.image.repository }}:{{ .Values.wiremock_instance_local.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.wiremock_instance_local.initContainer.image.pullPolicy }}
          command: ["bash", "-c", "cp  -rf /data/mappings /home/wiremock/storage/mappings"]
          volumeMounts:
            - mountPath: /data/mappings
              name: mappings-volume
            - mountPath: /home/wiremock/storage/mappings
              name: mappings-data
        - name: copy-responses
          securityContext:
            {{- toYaml .Values.wiremock_instance_local.securityContext | nindent 12 }}
          image: "{{ .Values.wiremock_instance_local.initContainer.image.repository }}:{{ .Values.wiremock_instance_local.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.wiremock_instance_local.initContainer.image.pullPolicy }}
          command: ["bash", "-c", "cp  -rf /data/responses /home/wiremock/storage/__files"]
          volumeMounts:
            - mountPath: /data/responses
              name: responses-volume
            - mountPath: /home/wiremock/storage/__files
              name: responses-data
      {{- with .Values.wiremock_instance_local.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wiremock_instance_local.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wiremock_instance_local.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: mappings-data
          emptyDir: {}
        - name: responses-data
          emptyDir: {}
        - name: mappings-volume
          configMap:
            name: {{ include "wiremock.fullname" . }}-mappings-configs
        - name: responses-volume
          configMap:
            name: {{ include "wiremock.fullname" . }}-responses-configs
