{{- if .Values.wiremock_instance_local.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.wiremock_instance_local.ingress.name }}
  annotations:
    {{- if .Values.wiremock_instance_local.ingress.tlsEnabled }}
    # Ensure that the ingress controller is set up for TLS termination (using cert-manager or other mechanisms)
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    kubernetes.io/ingress.class: nginx
spec:
  {{- if .Values.wiremock_instance_local.ingress.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.wiremock_instance_local.ingress.host }}
      secretName: {{ .Values.wiremock_instance_local.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.wiremock_instance_local.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.wiremock_instance_local.service.name }}
                port:
                  number: {{ .Values.wiremock_instance_local.service.ports.port }}
{{- end }}
