apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wiremock_istance_local.service.name }}
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wiremock_istance_local.service.type }}
  ports:
    - port: {{ .Values.wiremock_istance_local.service.externalPort }}
      targetPort: {{ .Values.wiremock_istance_local.service.internalPort }}
      protocol: TCP
      name: {{ include "wiremock.fullname" . }}
  selector:
    {{- include "wiremock.selectorLabels" . | nindent 4 }}
