#spring-instance-local
spring_instance_local:
  image:
    repository: joaoferreira17/springboot-instance-image
    tag: 1.0.1
    pullPolicy: Always
  imagePullSecrets:
    enabled: false
  configMap:
    name: spring-instance-configmap-local
  deployment:
    name: spring-instance-deployment-local
    container:
      name: spring-instance-local
      port: 8081
  service:
    name: spring-instance-service-local
    type: LoadBalancer
    ports:
      port: 8081
      targetPort: 8081
  probes:
    liveness:
      initialDelaySeconds: 100
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 100
      periodSeconds: 10
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  ingress:
    name: spring-instance-ingress-local
    enabled: true
    host: "spring-instance.minikube.local"
    tls:
      enabled: false 



# mysql-instance-local
mysql_instance_local:
  image:
    repository: joaoferreira17/my-sql-instance-image
    tag: 1.0.0
    pullPolicy: IfNotPresent
  imagePullSecrets:
    enabled: false
  configMap:
    name: mysql-configmap-local
  deployment:
    name: mysql-deployment-local
    container:
      name: mysql-instance-local
      port: 3306
  service:
    name: mysql-service-local
    type: ClusterIP
    ports:
      port: 3306
      targetPort: 3306
  probes:
    liveness:
      # MySQL's startup time
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
      exec:
        command:
          - mysqladmin
          - ping
          - "-h"
          - "127.0.0.1"
    readiness:
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
      exec:
        command:
          - mysqladmin
          - ping
          - "-h"
          - "127.0.0.1"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  ingress:
    enabled: false
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    annotations: {}


# wiremock-istance-local
wiremock_instance_local:
  image:
    repository: wiremock/wiremock
    # Overrides the image tag whose default is the chart appVersion.
    tag: 3.8.0
    pullPolicy: IfNotPresent
  imagePullSecrets:
    enabled: false
  deployment:
    name: wiremock-instance-deployment-local
    container:
      name: wiremock-instance-local
      port: 8080
  args:
  - "--port=8080"
  - "--max-request-journal=1000"
  - "--local-response-templating"
  - "--root-dir=/home/wiremock/storage"
  service:
    name: wiremock-instance-local
    type: ClusterIP
    ports:
      port: 8080
      targetPort: 8080
  probes:
    liveness:
      initialDelaySeconds: 100
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 100
      periodSeconds: 10
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  ingress:
    name: wiremock-instance-ingress-local
    enabled: true
    hosts: wiremock-instance.minikube.local
    tls: 
      enabled: false

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80